### ISSUE TITLE
`test_get_cbuffer_sizes` fails on aarch64

### ISSUE THREAD

**Issue by itdaniher** [Blosc/python-blosc#137]
```python

======================================================================
FAIL: test_get_cbuffer_sizes (blosc.test.TestCodec)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/name/python/swbs/python-blosc/blosc/test.py", line 309, in test_get_cbuffer_sizes
    self.assertEqual(t, (1000000, 4354, 2**16))
AssertionError: Tuples differ: (1000000, 4338, 65536) != (1000000, 4354, 65536)

First differing element 1:
4338
4354

- (1000000, 4338, 65536)
?             ^^

+ (1000000, 4354, 65536)
?             ^^


----------------------------------------------------------------------
Ran 31 tests in 1.510s

FAILED (failures=1, skipped=1)
Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    packages = ['blosc'],
  File "/home/name/.virtualenvs/swbs/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/name/.virtualenvs/swbs/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/name/.virtualenvs/swbs/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/name/.virtualenvs/swbs/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
  File "/home/name/python/swbs/python-blosc/blosc/test.py", line 331, in run
    run(suite).wasSuccessful()
AssertionError
```

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
```

```
Linux rock64 4.4.77-rk3328 #29 SMP Mon Nov 20 03:26:28 CET 2017 aarch64 aarch64 aarch64 GNU/Linux
```
76b05cd260d76527c1fa6501f9a939c3b4241a57

**Comment by FrancescAlted** [comment]
I think this is a problem with the test: one cannot trust that the size of the codec will always be the same for all the different version of the codec and all the platforms.  Differences as small as 16 bytes as in this case, should be allowed indeed.
