### ISSUE TITLE
Error during build using installed cblosc

### ISSUE THREAD

**Issue by eamanu** [Blosc/python-blosc#235]
Hi,

I'm have this error when I try to install python-blosc using and installed c-blosc:
```
-- Build files have been written to: /home/eamanu/dev/python-blosc/_skbuild/linux-x86_64-3.8/cmake-build
Scanning dependencies of target blosc_extension
[ 50%] Building C object CMakeFiles/blosc_extension.dir/blosc/blosc_extension.c.o
[100%] Linking C shared module blosc_extension.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lblosc_static
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/blosc_extension.dir/build.make:103: blosc_extension.cpython-38-x86_64-linux-gnu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/blosc_extension.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbuild/setuptools_wrap.py", line 589, in setup
    cmkr.make(make_args, env=env)
  File "/usr/lib/python3/dist-packages/skbuild/cmaker.py", line 496, in make
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Source directory:
    /home/eamanu/dev/python-blosc
  Working directory:
    /home/eamanu/dev/python-blosc/_skbuild/linux-x86_64-3.8/cmake-build
Please see CMake's output for more information.
```

To avoid use of c-blosc local folder I comments the lines to avoid build the local c-blosc:

```# Todo: c-blosc provides a CMake package configuration file that we can build
# against if blosc is available on the system, etc.
find_package(blosc)
# if(NOT blosc_FOUND)
#set(BUILD_STATIC ON CACHE BOOL "Build a static version of the blosc library.")
#set(BUILD_SHARED OFF CACHE BOOL "Build a shared library version of the blosc library.")
#set(BUILD_TESTS OFF CACHE BOOL "Build test programs form the blosc compression library")
#set(BUILD_BENCHMARKS OFF CACHE BOOL "Build benchmark programs form the blosc compression library")
#set(CMAKE_POSITION_INDEPENDENT_CODE ON)
#add_subdirectory(c-blosc)
```

**Comment by FrancescAlted** [comment]
Uh, this needs some investigation.  Thanks for the report.

**Comment by eamanu** [comment]
Hi @FrancescAlted Thanks for the report.

The problem was that I'm packaging new release on Debian. And in Debian, c-blosc library is called 'blosc'
so I make this patch [0] and apparently fix the problem. I'm not sure if that is the solution or not. 


[0] https://salsa.debian.org/python-team/packages/python-blosc/-/blob/debian/master/debian/patches/0001-Add-patch-to-use-libblosc.patch

**Comment by ArchangeGabriel** [comment]
In case you missed it, there is now a way better solution: https://github.com/Blosc/python-blosc/blob/master/README.rst#compiling-with-an-installed-blosc-library (added by https://github.com/Blosc/python-blosc/pull/244).

**Comment by FrancescAlted** [comment]
Hope that https://github.com/Blosc/python-blosc/pull/244 fixes this.  If not, please reopen.
