### ISSUE TITLE
Cannot install blosc 1.11.0 on apple M1 machine

### ISSUE THREAD

**Issue by aemr3** [Blosc/python-blosc#312]
Installation of blosc version 1.11.0 on apple M1 machine fails with the following error:

```
(.env) ➜  testblosc pip install blosc==1.11.0
Collecting blosc==1.11.0
  Using cached blosc-1.11.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Temp/testblosc/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Temp/testblosc/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Temp/testblosc/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/0k/k8hy18dd4yl7r66y6yg35z8r0000gn/T/pip-build-env-_xly75du/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/0k/k8hy18dd4yl7r66y6yg35z8r0000gn/T/pip-build-env-_xly75du/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/0k/k8hy18dd4yl7r66y6yg35z8r0000gn/T/pip-build-env-_xly75du/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/0k/k8hy18dd4yl7r66y6yg35z8r0000gn/T/pip-build-env-_xly75du/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 84, in <module>
      KeyError: 'flags'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Old version don't have this issue.

**Comment by minseong-ringle** [comment]
I have same problem too.

**Comment by FrancescAlted** [comment]
There are new arm64 wheels in the PyPI repo.  Can you try again?

**Comment by aemr3** [comment]
> There are new arm64 wheels in the PyPI repo. Can you try again?

Yes, version 1.11.1 is working well. I am closing this issue. Thank you for the updates.

Test results:

```
python-blosc version: 1.11.1
Blosc version: 1.21.3 ($Date:: 2022-12-15 #$)
Compressors available: ['blosclz', 'lz4', 'lz4hc', 'zlib', 'zstd']
Compressor library versions:
  BloscLZ: 2.5.1
  LZ4: 1.9.4
  Zlib: 1.2.11
  Zstd: 1.5.2
Python version: 3.10.8 (main, Oct 21 2022, 22:22:30) [Clang 14.0.0 (clang-1400.0.29.202)]
Platform: Darwin-22.2.0-arm64 (Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000)
Processor: arm
Byte-ordering: little
Detected cores: 8
Number of threads to use by default: 8
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
test_all_compressors (__main__.TestCodec) ... ok
test_all_filters (__main__.TestCodec) ... ok
test_basic_codec (__main__.TestCodec) ... ok
test_bithuffle_leftovers (__main__.TestCodec) ... ok
test_bitshuffle_not_multiple (__main__.TestCodec) ... ok
test_cbuffer_validate (__main__.TestCodec) ... ok
test_cbuffer_validate_failures (__main__.TestCodec) ... ok
test_compress_exceptions (__main__.TestCodec) ... ok
test_compress_input_types (__main__.TestCodec) ... ok
test_compress_ptr_exceptions (__main__.TestCodec) ... ok
test_decompress_exceptions (__main__.TestCodec) ... ok
test_decompress_input_types (__main__.TestCodec) ... ok
test_decompress_input_types_as_bytearray (__main__.TestCodec) ... ok
test_decompress_ptr_exceptions (__main__.TestCodec) ... ok
test_decompress_ptr_input_types (__main__.TestCodec) ... ok
test_decompress_releasegil (__main__.TestCodec) ... ok
test_get_blocksize (__main__.TestCodec) ... ok
test_get_cbuffer_sizes (__main__.TestCodec) ... ok
test_get_clib (__main__.TestCodec) ... ok
test_no_leaks (__main__.TestCodec) ... ok
test_pack_array_exceptions (__main__.TestCodec) ... ok
test_set_nthreads_exceptions (__main__.TestCodec) ... ok
test_unpack_array_exceptions (__main__.TestCodec) ... ok
test_unpack_array_with_from_py27_exceptions (__main__.TestCodec) ... ok
test_unpack_array_with_unicode_characters (__main__.TestCodec) ... ok
test_unpack_array_with_unicode_characters_from_py27 (__main__.TestCodec) ... ok
cbuffer_validate (blosc.toplevel)
Doctest: blosc.toplevel.cbuffer_validate ... ok
compress (blosc.toplevel)
Doctest: blosc.toplevel.compress ... ok
compress_ptr (blosc.toplevel)
Doctest: blosc.toplevel.compress_ptr ... ok
decompress (blosc.toplevel)
Doctest: blosc.toplevel.decompress ... ok
decompress_ptr (blosc.toplevel)
Doctest: blosc.toplevel.decompress_ptr ... ok
free_resources (blosc.toplevel)
Doctest: blosc.toplevel.free_resources ... ok
get_blocksize (blosc.toplevel)
Doctest: blosc.toplevel.get_blocksize ... ok
get_cbuffer_sizes (blosc.toplevel)
Doctest: blosc.toplevel.get_cbuffer_sizes ... ok
pack_array (blosc.toplevel)
Doctest: blosc.toplevel.pack_array ... ok
set_blocksize (blosc.toplevel)
Doctest: blosc.toplevel.set_blocksize ... ok
set_nthreads (blosc.toplevel)
Doctest: blosc.toplevel.set_nthreads ... ok
set_releasegil (blosc.toplevel)
Doctest: blosc.toplevel.set_releasegil ... ok
unpack_array (blosc.toplevel)
Doctest: blosc.toplevel.unpack_array ... ok

----------------------------------------------------------------------
Ran 39 tests in 1.490s

OK
```
